#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Run this from the repo root: it upserts the repo-root .env that
# backend/app/config.py loads. Ports used: backend :8000, capture proxy :9000.
# Card for subscription tests: 4718 6091 0820 4366 (Test Cards for Subscriptions).

banner "Ticket 20 — real Razorpay halted-subscription slice"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Razorpay: test-mode API keys"
say "Wires the local backend to real Razorpay test mode (GATEWAY_BACKEND=razorpay)."
open_url "https://dashboard.razorpay.com/app/keys"
step "Top-left mode switch: make sure you are in TEST mode, not Live."
step "Under 'API Keys', click 'Generate Test Key' (or reuse an existing one)."
step "Copy the Key Id (starts rzp_test_)."
ask RAZORPAY_KEY_ID "Paste the Key Id:"
step "Copy the Key Secret shown in the same dialog (only shown once)."
ask_secret RAZORPAY_KEY_SECRET "Paste the Key Secret:"
write_env RAZORPAY_KEY_ID "$RAZORPAY_KEY_ID"
write_env RAZORPAY_KEY_SECRET "$RAZORPAY_KEY_SECRET"
write_env GATEWAY_BACKEND "razorpay"

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Webhook signing secret"
say "You pick this string. It goes in .env now and into the dashboard webhook"
say "in stage 6 — the two must match or HMAC verification (webhook_security.py) fails."
note "Any random string. e.g.  openssl rand -hex 16"
ask_secret RAZORPAY_WEBHOOK_SECRET "Enter a webhook secret:"
write_env RAZORPAY_WEBHOOK_SECRET "$RAZORPAY_WEBHOOK_SECRET"

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "Start the backend (real gateway)"
say "In a SEPARATE terminal, from backend/, on a DEDICATED db so this slice's"
say "one case is unambiguous (recovery.db already holds dev/demo cases):"
note "  cd backend"
note "  DATABASE_URL='sqlite:///./ticket20.db' SWEEP_ENABLED=false uv run uvicorn app.main:app --port 8000"
say "GATEWAY_BACKEND=razorpay + the keys come from the .env this wizard wrote."
say "SWEEP_ENABLED=false keeps the halted case OPEN for inspection."
pause "Press Enter once 'curl -s localhost:8000/cases' returns []."

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Start the capture proxy"
say "In a THIRD terminal, from the repo root:"
note "  export RAZORPAY_WEBHOOK_SECRET='<the secret from stage 2>'"
note "  python3 test-scripts/capture_halted_webhook.py --port 9000 --forward http://127.0.0.1:8000"
say "It records each delivery to test-scripts/captured/<ts>.json, HMAC-checks it,"
say "then forwards to the backend so one real delivery both captures AND creates the case."
pause "Press Enter once it prints 'listening on :9000'."

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Open the public tunnel"
say "In a FOURTH terminal:"
note "  ssh -R 80:localhost:9000 nokey@localhost.run"
step "Copy the https URL it prints (changes every session)."
ask RAZORPAY_WEBHOOK_URL "Paste the tunnel URL (no trailing slash):"
write_env RAZORPAY_WEBHOOK_URL "$RAZORPAY_WEBHOOK_URL"
note "The webhook endpoint is:  ${RAZORPAY_WEBHOOK_URL}/webhooks/subscription-halted"

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Register the webhook in the dashboard"
open_url "https://dashboard.razorpay.com/app/webhooks"
step "Still in TEST mode. Click 'Add New Webhook' (or edit the ticket-17 one)."
step "Webhook URL:  ${RAZORPAY_WEBHOOK_URL}/webhooks/subscription-halted"
step "Secret: paste the SAME secret you entered in stage 2."
step "Under 'Active Events', tick  subscription.halted  (only that is needed here)."
step "Save / Create."
confirm "Webhook saved with subscription.halted active and the matching secret?" \
  || warn "Fix it before continuing — deliveries will 400 on signature otherwise."

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Create and authenticate a test subscription"
open_url "https://dashboard.razorpay.com/app/subscriptions"
step "Need a Plan first: https://dashboard.razorpay.com/app/plans → create any test plan."
step "Subscriptions → 'New Subscription' on that plan → 'Generate Subscription Link'."
step "Open the link, pay the authentication transaction with card 4718 6091 0820 4366"
step "  (any future expiry, any CVV, OTP 1234). The generic 4111 1111 1111 1111 card"
step "  is rejected for mandates — use 4718 6091 0820 4366."
confirm "Subscription shows status 'active' in the dashboard?" \
  || warn "Do not proceed until it is active."

# ── Stage 8 ──────────────────────────────────────────────────────────────
stage "Drive the subscription to 'halted'"
say "On the subscription's detail page (test mode only):"
step "Click 'Charge this now' → choose 'Failure'. Repeat FOUR times."
note "3 failures keep it 'active'; the 4th flips active → halted directly (docs:"
note "razorpay.com/docs/payments/subscriptions/test/ — 'fail 4 times in a row')."
confirm "Subscription status is now 'halted'?" \
  || warn "Re-check: reload the page; the transition can lag a few seconds."

# ── Stage 9 ──────────────────────────────────────────────────────────────
stage "Verify capture + case, then wire the regression fixture"
say "The capture proxy terminal should have logged one 'captured ...' line and"
say "'forwarded ... -> 200'. Now, from the repo root:"
note "  # newest capture -> the committed fixture (edit to scrub any real PII first):"
note "  python3 -c \"import json,glob,os; f=max(glob.glob('test-scripts/captured/*.json'),key=os.path.getmtime); json.dump(json.load(open(f))['body_json'], open('backend/tests/fixtures/real_subscription_halted.json','w'), indent=2)\""
note "  cd backend && uv run pytest tests/test_real_subscription_halted.py -q"
note "  uv run pytest tests/test_webhook_event_source.py -q"
say "Then eyeball the created case:"
note "  curl -s localhost:8000/cases | python3 -m json.tool"
step "Confirm: exactly one case, workflow_type 'halted_subscription', source 'real'."
step "Note any KeyError / 400 from the replay test — that is a real-vs-synthetic"
step "  payload-shape drift in webhooks._extract_halted_subscription to fix."
pause "Press Enter when the fixture is saved and the replay test has run."

# ── Stage 10 ─────────────────────────────────────────────────────────────
stage "Dedupe check + decision-cycle outcome"
say "Dedupe: in the dashboard webhook view, open the delivery log for this event"
say "and click 'Resend'. Razorpay reuses the same x-razorpay-event-id."
note "  curl -s localhost:8000/cases | python3 -m json.tool   # still exactly one case"
say ""
say "Decision cycle: inspect the one case's history entries —"
note "  curl -s localhost:8000/cases | python3 -m json.tool | less"
step "Record, from the 'decision' and 'execution' (or their absence) entries:"
say "  • what decide() picked: RESUME_CHARGE or NO_ACTION (cold-start cell is probabilistic)"
say "  • if RESUME_CHARGE executed: the RazorpayGateway.resume_charge result status,"
say "    or the GatewayError text if Razorpay rejected /subscriptions/<id>/resume"
say "  • whether an allocation_check entry exists (case_value 0 → usually not)"
say ""
say "Paste this filled-in block back to the agent — it goes into the research doc"
say "(Addendum 3) and the project-ticket17 memory; no green result is required."
cat <<'RESULTS'
  ─────────────────────────────────────────────
  Ticket 20 result (fill in):
    halted transition confirmed in dashboard : yes / no
    subscription.halted webhook received      : yes / no  (capture file: ______)
    HMAC signature_valid in capture           : true / false
    payload shape vs _extract_halted_*        : match / drift (____________)
    RecoveryCase created                      : count ___, workflow_type ___, source ___
    event-id dedupe on resend                 : still 1 case? yes / no
    decide() picked                           : resume_charge / no_action
    resume_charge outcome                     : status "____" / GatewayError "____" / n/a
    Payment-Links used out of 30              : ___
  ─────────────────────────────────────────────
RESULTS

finish
